### ISSUE TITLE
Variance

### ISSUE THREAD

**Issue by judyfong** [Einfaldlega-Hugmyndir/Compound_Interest_Calculator#7]
This one has a variance component what do you think about adding something like this in the future? https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator

**Comment by afk0901** [comment]
@judyfong I can see how this could be useful, like, if the user happens to know where the interests are going the user can predict a bit by this variance. Seems like it's useful for example for loans, investments, and economic analysis at least. So yeah, it would probably be great.

**Comment by judyfong** [comment]
Ok so then it’s a question of something youre personally interested in
adding or whether you want to wait to be paid to do it

**Comment by afk0901** [comment]
I would not mind waiting. I'm estimating an hour. Adding and subtraction, the field, and showing the results as a text somewhere on the page.

**Comment by judyfong** [comment]
Good then the patreon, buyme a coffee or paypal page would be useful now.
Want to use my paypal page?

**Comment by afk0901** [comment]
@judyfong I underestimated the task drastically. I may have forgotten to count in the creation of tests and debugging time and also it was just way off in general apparently. It took 4 hours instead of 1 hour. But anyway, it's deployed on the [gh page](https://afk0901.github.io/Compound_Interest_Calculator/). You may have to clear the cache if it's not showing anything new.

I made a [buy me a coffee page](https://buymeacoffee.com/afk0901). The more I think about it to put it on the compound interest page as you were suggesting, the more it does not make sense as it's not a personal project or not only me involved in it.

**Comment by afk0901** [comment]
I just added a Buy me a coffee link (button) on the gh-page now and in the Readme.

**Comment by judyfong** [comment]
@afk0901 this is missing the inspiration bit in the readme file liek you have said about networthify and moneychimp

**Comment by afk0901** [comment]
@judyfong That's right. I have fixed it now.

**Comment by judyfong** [comment]
Also variance doesn't allow variances under 1%

**Comment by judyfong** [comment]
The one on .gov does allow it.

**Comment by afk0901** [comment]
@judyfong Fixed. Also fixed the issue you could put - everywhere in the number as .Gov only takes positive values for these fields, and putting a - in middle of number does not make sense.

**Comment by judyfong** [comment]
Agreed

**Comment by judyfong** [comment]
I think it's time to close this as completed
